export default {
  ticketStatus: {
    "1": "Open",
    "2": "Development",
    "3": "Ready for QA",
    "4": "Test",
    "5": "Closed",
  },
  projectPosition: {
    "1": "PM",
    "2": "Developer",
    "3": "QA",
  },
  Loc: {
    "1": "New York",
    "2": "London",
    "3": "Kharkiv",
    "4": "St.Petersburg",
    "5": "Voronezh",
    "6": "Kherson",
    "7": "Zug",
    "8": "Kyiv",
    "9": "Dnepr",
    "10": "Odessa",
    "11": "Lublin",
    "12": "Buenos Aires",
    "13": "Wroclaw",
    "14": "Riga",
    "15": "Sofia",
    "16": "Wroclaw",
  },
  Level: {
    "1": "Trainee",
    "2": "Junior",
    "3": "Middle",
    "4": "Senior",
  },
  ticketType: {
    "1": "Technical Task",
    "2": "Bug",
    "3": "Improvement",
    "4": "New feature",
    "5": "Task",
  },
  skillName: {
    "1": ".NET",
    "2": "Java",
    "3": "Javascript",
    "4": "HTML",
    "5": "CSS",
    "7": "Ruby",
    "8": "Python",
    "9": "SQL",
  }
}
